version: '{build}'
skip_tags: true
image: Visual Studio 2015
configuration: Release
install:
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=841686','dotnet-core-sdk.exe')
  - ps: Write-Host "Installing .NET Core SDK..."
  - ps: Invoke-Command -ScriptBlock { ./dotnet-core-sdk.exe /S /v/qn }
  - ps: Write-Host "Installation succeeded." -ForegroundColor Green  
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Slalom.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: sY7tVlCO7MiUuEI/m2MeYMwvmLKZj2ORZyZ5wAxWLzBOIyfLcsp+vGerXS4lgi54
  skip_symbols: true
  on:
    branch: /^(master|develop)$/
- provider: GitHub
  auth_token:
    secure: ORG14NgkeG6aggB7c3a5yBcere+xl6LEOUCIL6+89ovQA69YXUbRSKn26eGq9hD4
  artifact: /Slalom.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master